package com.TwoTempate.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.TwoTempate.domain.core.Test;

import com.TwoTempate.dao.mysql.OrangeTestDefaultActivityDao;

import com.TwoTempate.domain.core.TwUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("OrangeTestDefaultActivityService")
public class OrangeTestDefaultActivityService extends TwBaseService  {
private static Logger log = Logger.getLogger(OrangeTestDefaultActivityService.class.getName());

	private OrangeTestDefaultActivityDao OrangeTestDefaultActivity_dao;


	public OrangeTestDefaultActivityDao get_OrangeTestDefaultActivity_dao() {
		return OrangeTestDefaultActivity_dao;
	}


	@Resource(name="OrangeTestDefaultActivityDao")
	public void set_OrangeTestDefaultActivity_dao(OrangeTestDefaultActivityDao OrangeTestDefaultActivity_dao) {
		this.OrangeTestDefaultActivity_dao = OrangeTestDefaultActivity_dao;
	}





}