package com.TwoTempate.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;
import org.apache.log4j.*;



import com.TwoTempate.domain.core.Test;

import com.TwoTempate.dao.mysql.RedActionDefaultActivityDao;

import com.TwoTempate.domain.core.TwUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("RedActionDefaultActivityService")
public class RedActionDefaultActivityService extends TwBaseService  {
private static Logger log = Logger.getLogger(RedActionDefaultActivityService.class.getName());

	private RedActionDefaultActivityDao RedActionDefaultActivity_dao;


	public RedActionDefaultActivityDao get_RedActionDefaultActivity_dao() {
		return RedActionDefaultActivity_dao;
	}


	@Resource(name="RedActionDefaultActivityDao")
	public void set_RedActionDefaultActivity_dao(RedActionDefaultActivityDao RedActionDefaultActivity_dao) {
		this.RedActionDefaultActivity_dao = RedActionDefaultActivity_dao;
	}





}