package com.TwoTempate.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.apache.log4j.*;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.TwoTempate.domain.core.Test;

import com.TwoTempate.config.TwoTempateSwaggerUIConstants;

import com.TwoTempate.service.RedActionDefaultActivityService;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/RedActionDefaultActivity", description = "RedActionDefaultActivity of RedActionDefaultActivity",produces = "application/json")
@CrossOrigin
@Controller("RedActionDefaultActivityController")
@RequestMapping("/RedActionDefaultActivity")
public class RedActionDefaultActivityController extends TwBaseController implements TwoTempateSwaggerUIConstants {

private static Logger log = Logger.getLogger(RedActionDefaultActivityController.class.getName());

	private RedActionDefaultActivityService RedActionDefaultActivity_service;


	public RedActionDefaultActivityService get_RedActionDefaultActivity_service() {
		return RedActionDefaultActivity_service;
	}


	@Resource(name="RedActionDefaultActivityService")
	public void set_RedActionDefaultActivity_service(RedActionDefaultActivityService RedActionDefaultActivity_service) {
		this.RedActionDefaultActivity_service = RedActionDefaultActivity_service;
	}






}